name: Daily Nurse Job Search

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  search-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run nurse job search
      run: |
        python nurse_job_search.py
        
    - name: Generate XML feed
      run: |
        python generate_xml_feed.py
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Commit and push results
      run: |
        git add job_results/ nurses_jobs_feed.xml
        git diff --staged --quiet || (git commit -m "Daily nurse jobs update - $(date)" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 